apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJkb2NrZXItaHViLnB0c2VjdXJpdHkucnU6NDYzIjoge30sCgkJImRvY2tlci1wdGNlcnQucHRzZWN1cml0eS5ydSI6IHt9LAoJCSJkb2NrZXItc3AucHRzZWN1cml0eS5ydTo0NjMiOiB7fSwKCQkiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIjoge30sCiAgICAgICAgICAgICAgICAiZ2hjci5pbyI6IHsiYXV0aCI6ICJibXQxZW01bGRITnZkbUU2WjJod1h6WlZkSEozVUZwSVpVSlRaRGs0V0RKd05IQkRXVlJDZVZoNU9FSmtZekZrU1U5T1lnPT0ifQoJfSwKCSJjcmVkc1N0b3JlIjogImRlc2t0b3AiCn0=
type: kubernetes.io/dockerconfigjson
